package Ventanas;

import Clases.Caja;
import Clases.Conexion;
import Clases.Fechas;
import Clases.Fondo;
import Clases.FormatoPesos;
import Clases.ImagenBoton;
import Clases.Imagenes;
import Clases.Validaciones;
import Clases.cliente;
import Clases.formaPagoInsert;
import static Ventanas.Ventas.jLabelNoVenta;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author harolD
 */
public class FormaPago extends javax.swing.JDialog {

    /**
     * Creates new form FormaPago
     */
    public FormaPago(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        m = true;
        Fondo fondo = new Fondo("Dialogos.jpg");
        this.setContentPane(fondo);
        this.setUndecorated(true);
        initComponents();
        new ImagenBoton("cerrar.png", JBotonCerrar, JBotonCerrar.getBounds().width, JBotonCerrar.getBounds().height);
        Shape p = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        this.setShape(p);
        new Imagenes("efectivo.png", jLabelEfectivo, 73, 73);
        new Imagenes("tarjeta-de-debito.png", jLabelCredito, 73, 73);
        new Imagenes("codigo-qr.png", jLabelQr, 73, 73);
        jTextFieldCambio.setText("0");
        jTextFieldEfectivo.setText("0");
        jTextFieldEfectivo.requestFocus();
        setTitle("Forma de Pago");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldEfectivo = new javax.swing.JTextField();
        efectivo = new javax.swing.JButton();
        credito = new javax.swing.JButton();
        QR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCambio = new javax.swing.JTextField();
        jLabelEfectivo = new javax.swing.JLabel();
        jLabelQr = new javax.swing.JLabel();
        jLabelCredito = new javax.swing.JLabel();
        JBotonCerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Efectivo:");

        jTextFieldEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextFieldEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEfectivoKeyReleased(evt);
            }
        });

        efectivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        efectivo.setText("Efectivo");
        efectivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                efectivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                efectivoMouseExited(evt);
            }
        });
        efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivoActionPerformed(evt);
            }
        });

        credito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        credito.setText("Credito");
        credito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditoMouseExited(evt);
            }
        });
        credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoActionPerformed(evt);
            }
        });

        QR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QR.setText("Pago QR");
        QR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QRMouseExited(evt);
            }
        });
        QR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QRActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cambio");

        jTextFieldCambio.setEditable(false);
        jTextFieldCambio.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jLabelEfectivo.setText("jLabel3");

        jLabelQr.setText("jLabel3");

        jLabelCredito.setText("jLabel3");

        JBotonCerrar.setBorder(null);
        JBotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonCerrarActionPerformed(evt);
            }
        });

        jButton1.setText("Multiple Forma de Pagp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEfectivo)
                                    .addComponent(jTextFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(213, 213, 213)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(efectivo)
                                .addComponent(jLabelEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(credito)
                            .addComponent(QR)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelQr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBotonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(efectivo)
                .addGap(0, 0, 0)
                .addComponent(jLabelEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(credito)
                .addGap(0, 0, 0)
                .addComponent(jLabelCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(QR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelQr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void efectivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_efectivoMouseEntered
        efectivo.setBackground(Color.green);
    }//GEN-LAST:event_efectivoMouseEntered

    private void efectivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_efectivoMouseExited
        efectivo.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_efectivoMouseExited

    private void creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoActionPerformed
        double total = Double.valueOf(Ventas.jTextFieldTotal.getText().replace(",", ""));
        Ventas.venta(Double.parseDouble(jTextFieldCambio.getText()), Double.parseDouble(jTextFieldEfectivo.getText()), total, "Credito");
        Ventas.detalleVenta();
        if(Ventas.tipoventa){
            total=-Ventas.saldo;
        }
        formaPagoInsert formapago = new formaPagoInsert();
        formapago.insetFormaPago(Integer.parseInt(Ventas.jLabelNoVenta.getText()), "Credito", total);
        dispose();
        i = 2;
    }//GEN-LAST:event_creditoActionPerformed

      public void SaldoCliente(double saldo) {
        try (Connection cn = Conexion.Conexion()) {
            PreparedStatement ps = cn.prepareStatement("UPDATE clientes SET Saldo = ? WHERE (Cedula = ?)");
            ps.setDouble(1, saldo);
            ps.setString(2, Ventas.jTextFieldCedula.getText());
            ps.executeUpdate();
            cn.close();

        } catch (SQLException e) {
            System.out.println(e);
        }
    }
    private void creditoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditoMouseEntered
        credito.setBackground(Color.green);
    }//GEN-LAST:event_creditoMouseEntered

    private void creditoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditoMouseExited
        credito.setBackground(new Color(78, 80, 82));        // TODO add your handling code here:
    }//GEN-LAST:event_creditoMouseExited

    private void QRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QRMouseEntered
        QR.setBackground(Color.green);        // TODO add your handling code here:
    }//GEN-LAST:event_QRMouseEntered

    private void QRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QRMouseExited
        QR.setBackground(new Color(78, 80, 82));
    }//GEN-LAST:event_QRMouseExited
    public int i = 0;
    private void efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivoActionPerformed
        double cambio = Double.parseDouble(jTextFieldCambio.getText().replace(",", ""));
        double efecty = Double.parseDouble(jTextFieldEfectivo.getText().replace(",", ""));
       
        Ventas.venta(cambio, efecty, 0, "Cancelado");
        Ventas.detalleVenta();
        formaPagoInsert formapago = new formaPagoInsert();
        formapago.insetFormaPago(Integer.parseInt(Ventas.jLabelNoVenta.getText()), "Efectivo",efecty);
        i = 1;
        dispose();
    }//GEN-LAST:event_efectivoActionPerformed

    private void QRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QRActionPerformed
        Ventas.venta(Double.parseDouble(jTextFieldCambio.getText().replace(",", "")), Double.parseDouble(jTextFieldEfectivo.getText().replace(",", "")), 0, "Cancelado");
        Ventas.detalleVenta();
        formaPagoInsert formapago = new formaPagoInsert();
        formapago.insetFormaPago(Integer.parseInt(Ventas.jLabelNoVenta.getText()), "PAGO QR", Double.parseDouble(Ventas.jTextFieldTotal.getText().replace(",", "")));

        dispose();
        i = 3;
    }//GEN-LAST:event_QRActionPerformed
    public static boolean m = true;
    private void JBotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonCerrarActionPerformed
        Object[] opc = new Object[]{"SI", "NO"};
        int i = JOptionPane.showOptionDialog(null, "¿Desea cancelar la Venta?", "salir", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opc, opc[0]);
        if (i == 0) {
            m = false;
            this.dispose();
        }
    }//GEN-LAST:event_JBotonCerrarActionPerformed

    private void jTextFieldEfectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEfectivoKeyReleased
        if (!"".equals(jTextFieldEfectivo.getText()) && !Validaciones.validarString(evt)) {
            double efectiv;
            efectiv = Double.parseDouble(jTextFieldEfectivo.getText().replace(",", ""));
            double total = Double.parseDouble(Ventas.jTextFieldTotal.getText().replace(",",""));

            if (Ventas.tipoventa) {
                total -= Ventas.saldo;
            }
            jTextFieldEfectivo.setText(FormatoPesos.formato(Double.parseDouble(jTextFieldEfectivo.getText().replace(",", ""))));
            jTextFieldCambio.setText(FormatoPesos.formato(efectiv - total));
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEfectivoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        m = false;
        variosFormaPago formaPago = new variosFormaPago((Frame) this.getParent(), true);
        formaPago.setTotalFactura(Double.parseDouble(Ventas.jTextFieldTotal.getText().replace(",", "")));
        formaPago.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    void SumarCaja(double precio) {
        try {
            double valor = new Caja().cajaTotal();
            double total = valor + precio;
            Connection cn = Conexion.Conexion();
            PreparedStatement ps = cn.prepareStatement("insert into caja (id,concepto,valor,total,fecha,hora) values (?,?,?,?,?,?)");
            ps.setInt(1, 0);
            ps.setString(2, "factura #" + jLabelNoVenta.getText());
            ps.setDouble(3, precio);
            ps.setDouble(4, total);
            ps.setDate(5, new Date(Fechas.fechaActualDate().getTime()));
            ps.setTime(6, new Time(Fechas.fechaActualDate().getTime()));
            ps.executeUpdate();
            cn.close();
            Administrador.jLabelCaja.setText(FormatoPesos.formato(total));
        } catch (NumberFormatException | SQLException e) {
            System.err.println("Error al Sumar Caja: " + e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBotonCerrar;
    private javax.swing.JButton QR;
    private javax.swing.JButton credito;
    private javax.swing.JButton efectivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCredito;
    private javax.swing.JLabel jLabelEfectivo;
    private javax.swing.JLabel jLabelQr;
    private javax.swing.JTextField jTextFieldCambio;
    private javax.swing.JTextField jTextFieldEfectivo;
    // End of variables declaration//GEN-END:variables

    void SumarCuentas(double precio) {
        try {
            double valor = new Caja().cuentasTotal();
            double total = valor + precio;
            Connection cn = Conexion.Conexion();
            PreparedStatement ps = cn.prepareStatement("insert into ptm( id,concepto,valor,total,fecha,hora) values (?,?,?,?,?,?)");
            ps.setInt(1, 0);
            ps.setString(2, "factura #" + jLabelNoVenta.getText());
            ps.setDouble(3, precio);
            ps.setDouble(4, total);
            ps.setDate(5, new Date(Fechas.fechaActualDate().getTime()));
            ps.setTime(6, new Time(Fechas.fechaActualDate().getTime()));
            ps.executeUpdate();
            cn.close();
            Administrador.jLabelPtm.setText(FormatoPesos.formato(total));
        } catch (NumberFormatException | SQLException e) {
            System.err.println("Error al Sumar Caja: " + e);
        }
    }
}
