/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Conexion;
import Clases.Fondo;
import Clases.FormatoPesos;
import Clases.FormatoTablasNomina;
import Clases.Imprimir;
import Clases.Validaciones;
import Clases.uiJTabben;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class Nomina extends javax.swing.JFrame {

    /**
     * Creates new form Nomina
     */
    FormatoTablasNomina ft = new FormatoTablasNomina();

    public Nomina() {
        Fondo fondo = new Fondo("FondoMenu.jpg");
        this.setContentPane(fondo);
        initComponents();
        nroNomina();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        eventotabla();
        jTable1.setDefaultRenderer(Object.class, ft);
        jTabbedPane1.setUI(new uiJTabben());
        jButton4.setVisible(false);
    }

    public void buscarDetalle(String NroVenta) {
        limpiar();
        DefaultTableModel tabla = (DefaultTableModel) jTable1.getModel();
        String[] datos = new String[6];
        try {
            Connection cn = Conexion.Conexion();
            PreparedStatement pr2 = cn.prepareStatement("select concepto,descripcion,cant,devengo,deducido,total from detallenomina where NroNomina = ?");
            pr2.setString(1, NroVenta);
            ResultSet rs2 = pr2.executeQuery();
            while (rs2.next()) {
                for (int i = 0; i < datos.length; i++) {
                    datos[i] = rs2.getString(i + 1);
                }
                tabla.addRow(datos);

            }
            cn.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    void nroNomina() {
        int nro_venta = 0;
        try (Connection cn = Conexion.Conexion()) {
            PreparedStatement pr = cn.prepareStatement("select max(NroNomina) from nomina");
            ResultSet rs = pr.executeQuery();

            while (rs.next()) {
                nro_venta = rs.getInt(1);
                nro_venta++;
                jLabelNro.setText("" + nro_venta);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    public final void eventotabla() {
        jTable1.getModel().addTableModelListener((TableModelEvent e) -> {
            if (e.getType() == TableModelEvent.INSERT) {
                int row = e.getLastRow();
                cambiarCant(row);
                total();
            }
            if (e.getType() == TableModelEvent.UPDATE) {
                int columna = e.getColumn();
                int row = e.getLastRow();
                switch (columna) {
                    case 2 -> {
                        cambiarCant(row);
                        total();
                    }
                    case 4 -> {
                        cambiarCant(row);
                        total();
                    }
                    case 3 -> {
                        cambiarCant(row);
                        total();
                    }
                    default -> {
                    }
                }
            }
        });
    }

    public void cambiarCant(int row) {
        int cant = Integer.parseInt(jTable1.getValueAt(row, 2).toString());
        double precio = Double.parseDouble(jTable1.getValueAt(row, 3).toString());

        double precio2 = Double.parseDouble(jTable1.getValueAt(row, 4).toString());
        double total1 = precio * cant + precio2 * cant;

        jTable1.setValueAt(total1, row, 5);

    }

    public void total() {
        double t = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            t += Double.parseDouble(jTable1.getValueAt(i, 5).toString());

        }
        jLabelTotal.setText(FormatoPesos.formato(t));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldValorDeven = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldConceptoDeven = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDescripDeven = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCantDv = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldValorDed = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldConceptoDed = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDescripcionDed = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldCantDed = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("No. Nomina:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("C.C:");

        jLabelNro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNro.setText("0");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha:");

        jTextFieldCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCedulaKeyPressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setOpaque(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Concepto:");

        jTextFieldValorDeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorDevenActionPerformed(evt);
            }
        });
        jTextFieldValorDeven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValorDevenKeyPressed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor:");

        jTextFieldConceptoDeven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldConceptoDevenKeyPressed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descripción:");

        jTextFieldDescripDeven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDescripDevenKeyPressed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cant/horas:");

        jTextFieldCantDv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCantDvKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorDeven, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldConceptoDeven, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCantDv, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jTextFieldDescripDeven))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConceptoDeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldDescripDeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorDeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCantDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Devengo", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setOpaque(false);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Concepto:");

        jTextFieldValorDed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValorDedKeyPressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Valor:");

        jTextFieldConceptoDed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldConceptoDedKeyPressed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Descripción:");

        jTextFieldDescripcionDed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionDedKeyPressed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cant/horas:");

        jTextFieldCantDed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCantDedKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldConceptoDed, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldValorDed, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescripcionDed, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantDed, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConceptoDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldDescripcionDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldValorDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldCantDed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Deduccion", jPanel2);

        jScrollPane1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Concepto", "Descripcion", "Cant/horas", "Devengado", "Deducido", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setOpaque(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(500);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total:");

        jLabelTotal.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTotal.setText("$0");
        jLabelTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelTotal.setOpaque(true);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("-");

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Imprimir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(219, 219, 219)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNro)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel4))
                            .addComponent(jTextFieldCedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabelNro)
                        .addComponent(jLabel4))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabelTotal)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static int i = 0;
    private void jTextFieldConceptoDevenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConceptoDevenKeyPressed
        i = 1;
        if (!Validaciones.validarEnter(evt)) {
            buscarConNomina(jTextFieldConceptoDeven.getText().trim());
        }
    }//GEN-LAST:event_jTextFieldConceptoDevenKeyPressed

    private void jTextFieldCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCedulaKeyPressed
        if (!Validaciones.validarEnter(evt)) {
            buscarEmpleado();
        }
    }//GEN-LAST:event_jTextFieldCedulaKeyPressed
    
    private void jTextFieldDescripDevenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripDevenKeyPressed
        if (!Validaciones.validarEnter(evt)) {
            jTextFieldValorDeven.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldDescripDevenKeyPressed

    private void jTextFieldValorDevenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorDevenKeyPressed
        if (!Validaciones.validarEnter(evt)) {
            jTextFieldCantDv.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorDevenKeyPressed

    private void jTextFieldCantDvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantDvKeyPressed
        if (!Validaciones.validarEnter(evt)) {
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            Object[] datos = new Object[6];
            datos[0] = jTextFieldConceptoDeven.getText();
            datos[1] = jTextFieldDescripDeven.getText();
            datos[2] = jTextFieldCantDv.getText();
            datos[3] = jTextFieldValorDeven.getText();
            datos[4] = 0;
            datos[5] = (Double.parseDouble(jTextFieldValorDeven.getText().trim()) * Double.parseDouble(jTextFieldCantDv.getText().trim()));

            df.addRow(datos);

            total();

            jTextFieldCantDed.setText("");
            jTextFieldCantDv.setText("");
            jTextFieldConceptoDed.setText("");
            jTextFieldConceptoDeven.setText("");
            jTextFieldDescripDeven.setText("");
            jTextFieldDescripcionDed.setText("");
            jTextFieldValorDed.setText("");
            jTextFieldValorDeven.setText("");
        }
    }//GEN-LAST:event_jTextFieldCantDvKeyPressed

    private void jTextFieldCantDedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantDedKeyPressed
        if (!Validaciones.validarEnter(evt)) {
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            Object[] datos = new Object[6];
            datos[0] = jTextFieldConceptoDed.getText();
            datos[1] = jTextFieldDescripcionDed.getText();
            datos[2] = jTextFieldCantDed.getText();
            datos[4] = "-" + jTextFieldValorDed.getText();
            datos[3] = 0;

            df.addRow(datos);
            jTextFieldValorDed.setText("");
            jTextFieldCantDed.setText("");
            jTextFieldDescripcionDed.setText("");
            jTextFieldConceptoDed.setText("");
        }
    }//GEN-LAST:event_jTextFieldCantDedKeyPressed

    private void jTextFieldDescripcionDedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionDedKeyPressed
        if (!Validaciones.validarEnter(evt)) {
            jTextFieldValorDed.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionDedKeyPressed

    private void jTextFieldValorDedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorDedKeyPressed
        if (!Validaciones.validarEnter(evt)) {
            jTextFieldCantDed.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorDedKeyPressed

    private void jTextFieldConceptoDedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConceptoDedKeyPressed
        i = 2;
        if (!Validaciones.validarEnter(evt)) {
            buscarConNomina(jTextFieldConceptoDed.getText());
        }
    }//GEN-LAST:event_jTextFieldConceptoDedKeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (!Validaciones.validarSuprimir(evt)) {
            DefaultTableModel tf = (DefaultTableModel) jTable1.getModel();
            int i = jTable1.getSelectedRow();
            tf.removeRow(i);
            total();
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jDateChooser1.getDate() != null && jDateChooser2.getDate() != null
                && jTable1.getRowCount() > 0 && !jLabel6.getText().equals("")) {
            nomina();
            detalleNomina();
            JOptionPane.showMessageDialog(this, "Se realizo la nomina de " + jLabel6.getText());
            limpiar();
            nroNomina();
        } else {
            JOptionPane.showMessageDialog(this, "Faltan Datos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int nr = Integer.parseInt(jLabelNro.getText());
        jButton4.setVisible(true);
        if (nr > 1) {
            limpiar();
            nr--;
            jLabelNro.setText("" + nr);
            buscarNomina(String.valueOf(nr));
            buscarDetalle(String.valueOf(nr));
            jButton1.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int nro = Integer.parseInt(jLabelNro.getText());

        try {
            Connection cn = Conexion.Conexion();
            PreparedStatement pr = cn.prepareStatement("select max(NroNomina) from nomina");
            ResultSet rs = pr.executeQuery();
            while (rs.next()) {

                int nur = rs.getInt(1);

                if (nur <= nro) {

                    jButton4.setVisible(false);
                    jTextFieldCedula.setEditable(true);
                    jTextFieldConceptoDed.setEditable(true);

                    jButton1.setVisible(true);
                    limpiar();
                    nroNomina();
                } else {
                    nro++;
                    jLabelNro.setText("" + nro);
                    limpiar();
                    buscarDetalle(String.valueOf(nro));
                    buscarNomina(String.valueOf(nro));
                }
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Imprimir().imprimirNomina(jLabelNro.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldValorDevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorDevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorDevenActionPerformed
    
    void buscarEmpleado() {
        try (Connection cn = Conexion.Conexion()) {
            PreparedStatement ps = cn.prepareStatement("select Nombre from empleados where Cedula= ?");
            ps.setString(1, jTextFieldCedula.getText().trim());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                jLabel6.setText(rs.getString(1));
            } else {
                new BuscarEmpleado(this, true).setVisible(true);
            }
            cn.close();
        } catch (SQLException ex) {

        }
    }
    
    void buscarNomina(String nro) {
        try (Connection cn = Conexion.Conexion()) {
            PreparedStatement ps = cn.prepareStatement("select * from nomina where NroNomina = ?");
            ps.setString(1, nro);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                jTextFieldCedula.setText(rs.getString(3));
                buscarEmpleado();
                jLabelTotal.setText(rs.getString(4));
                jDateChooser1.setDate(new java.util.Date(rs.getDate(5).getTime()));
                jDateChooser2.setDate(new java.util.Date(rs.getDate(6).getTime()));
            }
            cn.close();
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    void nomina() {
        try (Connection cn = Conexion.Conexion()) {
            PreparedStatement ps = cn.prepareStatement("INSERT INTO nomina (id,NroNomina,CC,Total,fecha1,fecha2) values(?,?,?,?,?,?)");
            ps.setInt(1, 0);;
            ps.setInt(2, Integer.parseInt(jLabelNro.getText().trim()));
            ps.setString(3, jTextFieldCedula.getText());
            ps.setDouble(4, Double.parseDouble(jLabelTotal.getText().replace(",", "")));
            ps.setDate(5, new Date(jDateChooser1.getDate().getTime()));
            ps.setDate(6, new Date(jDateChooser2.getDate().getTime()));
            ps.execute();
            cn.close();
        } catch (SQLException ex) {
            System.err.println("Error un subir nomina: " + ex);
            JOptionPane.showMessageDialog(this, "Error, No se puedo Subir nomina: " + ex);
        }
    }

    void detalleNomina() {
        try (Connection cn = Conexion.Conexion()) {
            PreparedStatement ps = cn.prepareStatement("INSERT INTO detallenomina (id,NroNomina,concepto,descripcion,cant,devengo,deducido,total) values(?,?,?,?,?,?,?,?)");
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                ps.setInt(1, 0);
                ps.setString(2, jLabelNro.getText());
                ps.setString(3, jTable1.getValueAt(i, 0).toString());
                ps.setString(4, jTable1.getValueAt(i, 1).toString());
                ps.setString(5, jTable1.getValueAt(i, 2).toString());
                ps.setString(6, jTable1.getValueAt(i, 3).toString());
                ps.setString(7, jTable1.getValueAt(i, 4).toString());
                ps.setString(8, jTable1.getValueAt(i, 5).toString());
                ps.execute();
            }
            cn.close();
        } catch (SQLException ex) {
            System.err.println("Error un subir nomina: " + ex);
            JOptionPane.showMessageDialog(this, "Error, No se puedo Subir nomina: " + ex);
        }
    }

    void limpiar() {
        DefaultTableModel tf = (DefaultTableModel) jTable1.getModel();
        for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
            tf.removeRow(i);
        }
        jTextFieldCedula.setText("");
        jLabel6.setText("");
        jTextFieldCantDed.setText("");
        jTextFieldCantDv.setText("");
        jTextFieldConceptoDed.setText("");
        jTextFieldConceptoDeven.setText("");
        jTextFieldDescripDeven.setText("");
        jTextFieldDescripcionDed.setText("");
        jTextFieldValorDed.setText("");
        jTextFieldValorDeven.setText("");
    }

    public void buscarConNomina(String Codigo) {
        try (Connection cn = Conexion.Conexion()) {
            PreparedStatement ps = cn.prepareStatement("select * from connomina where concepto=?");
            ps.setString(1, Codigo);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                if (i == 1) {
                    jTextFieldDescripDeven.setText(rs.getString(3));
                    jTextFieldDescripDeven.requestFocus();
                    i = 0;
                } else if (i == 2) {
                    jTextFieldDescripcionDed.setText(rs.getString(3));
                    jTextFieldDescripcionDed.requestFocus();
                    i = 0;
                }
            } else {
                new connomina().setVisible(true);
            }
            cn.close();
        } catch (SQLException ex) {
            System.err.println("Error al buscar nomina: " + ex);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelNro;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCantDed;
    private javax.swing.JTextField jTextFieldCantDv;
    public static javax.swing.JTextField jTextFieldCedula;
    public javax.swing.JTextField jTextFieldConceptoDed;
    public javax.swing.JTextField jTextFieldConceptoDeven;
    private javax.swing.JTextField jTextFieldDescripDeven;
    private javax.swing.JTextField jTextFieldDescripcionDed;
    private javax.swing.JTextField jTextFieldValorDed;
    private javax.swing.JTextField jTextFieldValorDeven;
    // End of variables declaration//GEN-END:variables
}
