/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Clases.Conexion;
import Clases.Fondo;
import Clases.ImagenBoton;
import Clases.Imagenes;
import Clases.TablaFondo;
import Clases.Validaciones;
import static Ventanas.Catalogo.sql;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author harol
 */
public class Servicios extends javax.swing.JFrame {

    /**
     * Creates new form Servicios
     */
    public Servicios() {Fondo fondo = new Fondo("FondoMenu.jpg");
        this.setContentPane(fondo);
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jCheckBoxCodigo.setContentAreaFilled(false);
        setLocationRelativeTo(null);
        new ImagenBoton("Agregar.gif", jButton1, jButton1.getHeight()-2, jButton1.getWidth()-2);
        jButton1.setContentAreaFilled(false);
        jTextFieldBusqueda.requestFocus();
        inventario();
        cerra();
    }


    public static void inventario() {
            sql = "select p.id,p.codigo,p.concepto,p.valor,"+
                    "u.nombre,p.FechaModificar from servicio p left join usuarios u on p.idUsuario = u.idusuarios";

        DefaultTableModel tabla = tabla(6);

        String[] datos = new String[6];
        try {
            Connection cnn = Conexion.Conexion();

            PreparedStatement pre = cnn.prepareStatement(sql);
            ResultSet rs = pre.executeQuery();

            while (rs.next()) {
                for (int i = 0; i < 6; i++) {
                    datos[i] = rs.getString(i + 1);
                }
                tabla.addRow(datos);
            }

        } catch (SQLException e) {
            System.err.println(e);
        }

    }
    
    public static DefaultTableModel tabla(int column) {
        DefaultTableModel tabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.addColumn("id");
        tabla.addColumn("Codigo");
        tabla.addColumn("Concepto");
        tabla.addColumn("Valor");
        tabla.addColumn("Usuario");
        tabla.addColumn("Fecha Modificado");

        Table.setModel(tabla);

        TableColumnModel columnModel = Table.getColumnModel();

        for (int i = 0; i < column; i++) {
            columnModel.getColumn(i).setPreferredWidth(150);
        }
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(2).setPreferredWidth(400);

        for (int i = 0; i < column; i++) {
            columnModel.getColumn(i).setResizable(false);
        }

        return tabla;
    }
    
    public void cerra() {
        try {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {

                    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    Ventas.m = false;
                }
            });
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new TablaFondo("FondoMenu.jpg");
        jTextFieldBusqueda = new javax.swing.JTextField();
        jCheckBoxCodigo = new javax.swing.JCheckBox();
        jCheckBoxNombre = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(null);
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setOpaque(false);

        Table.setAutoCreateRowSorter(true);
        Table.setBackground(new java.awt.Color(51, 153, 255));
        Table.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        Table.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Table.setForeground(new java.awt.Color(0, 51, 51));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table.setAutoscrolls(false);
        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table.setGridColor(new java.awt.Color(0, 153, 153));
        Table.setInheritsPopupMenu(true);
        Table.setOpaque(false);
        Table.setRowHeight(30);
        Table.setSelectionBackground(new java.awt.Color(0, 102, 102));
        Table.setSelectionForeground(new java.awt.Color(0, 153, 153));
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jTextFieldBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBusquedaKeyReleased(evt);
            }
        });

        jCheckBoxCodigo.setBackground(null);
        jCheckBoxCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxCodigo.setSelected(true);
        jCheckBoxCodigo.setText("Codigo");
        jCheckBoxCodigo.setBorder(null);
        jCheckBoxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCodigoActionPerformed(evt);
            }
        });

        jCheckBoxNombre.setBackground(null);
        jCheckBoxNombre.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxNombre.setSelected(true);
        jCheckBoxNombre.setText("Nombre Producto");
        jCheckBoxNombre.setBorder(null);
        jCheckBoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNombreActionPerformed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBusqueda))
                            .addComponent(jCheckBoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxNombre)
                            .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        String cod;
        int i = Table.getSelectedRow();

        if (evt.getClickCount() == 2) {
            if (Ventas.m) {
                cod = Table.getValueAt(i, 1).toString();
                Ventas.jTextFieldCodigo.setText(cod);
                this.dispose();
                Ventas.producto();
                Ventas.m = false;
            } else if (Compras.n) {
                cod = Table.getValueAt(i, 1).toString();
                Compras.jTextFieldCodigo.setText(cod);
                this.dispose();
                Compras.producto();
                Compras.n = false;
            } else if (Administrador.m) {
                int id = Integer.parseInt(Table.getValueAt(i, 0).toString());
                new Producto().setVisible(true);
                Producto.modificar(id);
                Producto.idp = id;
            }
        }

    }//GEN-LAST:event_TableMouseClicked

    private void TableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableKeyPressed
        if (Administrador.m) {
            if (!Validaciones.validarSuprimir(evt)) {
                try {
                    int k = JOptionPane.showConfirmDialog(null, "Desea eliminar Producto?", "Eliminar Producto", JOptionPane.YES_NO_OPTION);
                    if (k == 0) {
                        int i = Table.getSelectedRow();
                        Connection cn = Conexion.Conexion();
                        PreparedStatement pr = cn.prepareStatement("Delete from producto where (idProducto = ?)");
                        pr.setInt(1, Integer.parseInt(Table.getValueAt(i, 0).toString()));
                        pr.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Producto eliminado");
                    }
                } catch (NumberFormatException | SQLException e) {
                    System.err.println("Error Eliminar producto: " + e);
                }
            }
        }
    }//GEN-LAST:event_TableKeyPressed

    private void jTextFieldBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaKeyReleased
     
    }//GEN-LAST:event_jTextFieldBusquedaKeyReleased

    private void jCheckBoxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCodigoActionPerformed
 
    }//GEN-LAST:event_jCheckBoxCodigoActionPerformed

    private void jCheckBoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNombreActionPerformed

    }//GEN-LAST:event_jCheckBoxNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Servicio().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxCodigo;
    private javax.swing.JCheckBox jCheckBoxNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
